# ============================================================
# Kutumbly — KUTUMBLY SOVEREIGN OS
# Script: insert_all_missing_keys.py
# Inserts all missing i18n keys into lib/i18n.ts
# ============================================================

def make_entry(en, hi, bho, mr="", gu="", pa="", ta="", kn="", te="", ne="", bn="", mni=""):
    mr = mr or en; gu = gu or en; pa = pa or en; ta = ta or en
    kn = kn or en; te = te or en; ne = ne or en; bn = bn or en; mni = mni or en
    return {
        "en": en, "hi": hi, "mr": mr, "gu": gu, "pa": pa, "ta": ta,
        "bho": bho, "kn": kn, "te": te, "ne": ne, "bn": bn, "mni": mni
    }

MISSING = {
    "ADD_HOLDING": make_entry("Add Holding", "होल्डिंग जोड़ें", "होल्डिंग जोड़ीं"),
    "ADD_LEARNER": make_entry("Add Learner", "शिक्षार्थी जोड़ें", "सिखावे वाला जोड़ीं"),
    "ADD_RESOURCE": make_entry("Add Resource", "संसाधन जोड़ें", "साधन जोड़ीं"),
    "ADD_SAAMAN": make_entry("Add Item", "सामान जोड़ें", "सामान जोड़ीं"),
    "ADD_SUBJECT": make_entry("Add Subject", "विषय जोड़ें", "विषय जोड़ीं"),
    "ALL": make_entry("All", "सभी", "सब कुछ"),
    "ALL_CAUGHT_UP": make_entry("All caught up!", "सब ठीक है!", "सब ठीक बा!"),
    "AMOUNT_LABEL": make_entry("Amount", "राशि", "रकम"),
    "APPEARANCE": make_entry("Appearance", "रूप-रंग", "दिखावट"),
    "ASSET_CATEGORY": make_entry("Asset Category", "संपत्ति श्रेणी", "संपत्ति के किसिम"),
    "ASSET_CLASSES": make_entry("Asset Classes", "संपत्ति वर्ग", "संपत्ति के वर्ग"),
    "ASSET_NAME": make_entry("Asset Name", "संपत्ति का नाम", "संपत्ति के नाम"),
    "ASSIGNED_TO_LABEL": make_entry("Assigned To", "किसे सौंपा", "के के खातिर"),
    "ATTENDANCE": make_entry("Attendance", "उपस्थिति", "हाजिरी"),
    "BACKUP_EMAIL_HINT": make_entry("Optional backup contact", "वैकल्पिक बैकअप संपर्क", "बैकअप संपर्क"),
    "BACKUP_EMAIL_LABEL": make_entry("Backup Email", "बैकअप ईमेल", "बैकअप ईमेल"),
    "BACK_TO_LIST": make_entry("Back to List", "सूची पर वापस", "लिस्ट पर वापस"),
    "BALANCE_DUE": make_entry("Balance Due", "शेष देय", "बाकी पैसा"),
    "BIOMETRIC_ACTIVE": make_entry("Biometric Active", "बायोमेट्रिक सक्रिय", "बायोमेट्रिक चालू बा"),
    "BLOOD_SUGAR": make_entry("Blood Sugar", "रक्त शर्करा", "खून में चीनी"),
    "BOARD_PH": make_entry("e.g. CBSE, State", "जैसे CBSE, State", "जइसे CBSE, State"),
    "BOARD_TYPE": make_entry("Board Type", "बोर्ड प्रकार", "बोर्ड के किसिम"),
    "CANCEL": make_entry("Cancel", "रद्द करें", "रद्द करीं"),
    "CATEGORY_LABEL": make_entry("Category", "श्रेणी", "किसिम"),
    "CHANGE_EMAIL": make_entry("Change Email", "ईमेल बदलें", "ईमेल बदलीं"),
    "CHANGE_PIN": make_entry("Change PIN", "PIN बदलें", "PIN बदलीं"),
    "CHOOSE_LANG": make_entry("Choose Language", "भाषा चुनें", "भाषा चुनीं"),
    "CHOOSE_PIN_LABEL": make_entry("Choose a 6-digit PIN", "6 अंकों का PIN चुनें", "6 अंकन के PIN चुनीं"),
    "CLASS_PH": make_entry("e.g. Class 10", "जैसे कक्षा 10", "जइसे कक्षा 10"),
    "CLASS_STD": make_entry("Class / Standard", "कक्षा / मानक", "कक्षा"),
    "COMING_SOON": make_entry("Coming Soon", "जल्द आ रहा है", "जल्दी आई"),
    "COMPOSE_MEMOIR": make_entry("Compose Memoir", "संस्मरण लिखें", "यादें लिखीं"),
    "CONFIRM_PIN_LABEL": make_entry("Confirm PIN", "PIN की पुष्टि करें", "PIN फिर से लिखीं"),
    "CREATE_VAULT_SUB": make_entry("Set up your sovereign family vault", "अपना सॉवरेन परिवार वॉल्ट सेट करें", "अपना तिजोरी बनावा"),
    "CREATE_VAULT_TITLE": make_entry("Create Your Vault", "अपना वॉल्ट बनाएं", "अपना तिजोरी बनाईं"),
    "CRITICAL_ALERTS": make_entry("Critical Alerts", "महत्वपूर्ण अलर्ट", "जरूरी अलर्ट"),
    "CRITICAL_STOCK": make_entry("Critical Stock", "महत्वपूर्ण स्टॉक", "खतम होखे वाला माल"),
    "DANGER_ZONE": make_entry("Danger Zone", "खतरा क्षेत्र", "खतरा वाली जगह"),
    "DARK_MODE": make_entry("Dark Mode", "डार्क मोड", "डार्क मोड"),
    "DARK_MODE_SHORT": make_entry("Dark", "डार्क", "डार्क"),
    "DAYS_LEFT": make_entry("Days Left", "दिन शेष", "दिन बचल बा"),
    "DESC_LABEL": make_entry("Description", "विवरण", "बिबरन"),
    "DESC_PH": make_entry("Add a description...", "विवरण जोड़ें...", "बिबरन लिखीं..."),
    "DIARY": make_entry("Diary", "डायरी", "डायरी"),
    "DIARY_SUBTITLE": make_entry("Your private memories, encrypted.", "आपकी निजी यादें, एन्क्रिप्टेड।", "रउवा के निजी यादें, सुरक्षित।"),
    "DIASTOLIC": make_entry("Diastolic", "डायस्टोलिक", "डायस्टोलिक"),
    "DIFFICULTY": make_entry("Difficulty", "कठिनाई", "कठिनाई"),
    "DONE": make_entry("Done", "हो गया", "भइल"),
    "DOWNLOAD": make_entry("Download", "डाउनलोड", "डाउनलोड"),
    "DURATION_MINS": make_entry("Duration (mins)", "अवधि (मिनट)", "समय (मिनट)"),
    "DURATION_PH": make_entry("e.g. 45", "जैसे 45", "जइसे 45"),
    "ERROR_ENTER_NAME": make_entry("Please enter a name", "कृपया नाम दर्ज करें", "नाम लिखीं"),
    "ERROR_PIN_MATCH": make_entry("PINs do not match", "PIN मेल नहीं खाते", "PIN एक जइसन नाही बा"),
    "ERROR_PIN_REQ": make_entry("PIN is required", "PIN आवश्यक है", "PIN चाहीं"),
    "ESTIMATED_TOTAL": make_entry("Estimated Total", "अनुमानित कुल", "अनुमानित जोड़"),
    "EST_PRICE": make_entry("Est. Price", "अनुमानित मूल्य", "अनुमानित दाम"),
    "EXPENSES_LABEL": make_entry("Expenses", "खर्च", "खर्चा"),
    "EXPENSE_PROFILE": make_entry("Expense Profile", "खर्च प्रोफाइल", "खर्चा के हाल"),
    "FACTORY_RESET": make_entry("Factory Reset", "फ़ैक्टरी रीसेट", "पूरा रीसेट"),
    "FAMILY_GROCERY": make_entry("Family Grocery", "पारिवारिक किराना", "घर के किराना"),
    "FAMILY_LEDGER": make_entry("Family Ledger", "पारिवारिक खाता बही", "घर के हिसाब-किताब"),
    "FINALIZE_VAULT_BTN": make_entry("Finalize Vault", "वॉल्ट को अंतिम रूप दें", "तिजोरी बनाईं"),
    "FIRE_TARGET": make_entry("FIRE Target", "FIRE लक्ष्य", "FIRE के लक्ष्य"),
    "FOUNDER_JAWAHAR": make_entry("Jawahar R. Mallah", "जवाहर आर. मल्लाह", "जवाहर आर. मल्लाह"),
    "FOUNDER_PUSHPA": make_entry("Pushpa Mallah", "पुष्पा मल्लाह", "पुष्पा मल्लाह"),
    "FOUNDER_TITLE": make_entry("System Architect", "सिस्टम आर्किटेक्ट", "सिस्टम बनावे वाला"),
    "FULL_SCHEDULE": make_entry("Full Schedule", "पूरा कार्यक्रम", "पूरा कार्यक्रम"),
    "GENERIC_ERROR": make_entry("Something went wrong", "कुछ गलत हो गया", "कुछ गड़बड़ भइल"),
    "GIVEN_TOTAL": make_entry("Given Total", "कुल दिया गया", "कुल दिहल गइल"),
    "GOAL_DEADLINE": make_entry("Goal Deadline", "लक्ष्य की अंतिम तिथि", "लक्ष्य के तारीख"),
    "GOAL_PH": make_entry("e.g. Learn Algebra", "जैसे बीजगणित सीखें", "जइसे बीजगणित सीखीं"),
    "HARDWARE_ACTIVE": make_entry("Hardware Active", "हार्डवेयर सक्रिय", "हार्डवेयर चालू बा"),
    "HEALTH": make_entry("Health", "स्वास्थ्य", "सेहत"),
    "HEALTH_MEDS": make_entry("Medications", "दवाइयाँ", "दवाई"),
    "HEALTH_VITALS": make_entry("Vitals", "वाइटल्स", "सेहत के जानकारी"),
    "ICON_LABEL": make_entry("Icon", "आइकन", "आइकन"),
    "INSTITUTION_PH": make_entry("e.g. St. Xavier's School", "जैसे सेंट जेवियर स्कूल", "जइसे केऊ स्कूल"),
    "INVALID_FILE_ERROR": make_entry("Invalid file type", "अमान्य फ़ाइल प्रकार", "गलत फाइल"),
    "INVESTED_PRINCIPAL": make_entry("Invested Principal", "निवेशित मूलधन", "लगावल पैसा"),
    "INVITED": make_entry("Invited", "आमंत्रित", "बुलावल गइल"),
    "ITEMS_TO_BUY": make_entry("Items to Buy", "खरीदने के लिए सामान", "किने के सामान"),
    "ITEM_NAME": make_entry("Item Name", "सामान का नाम", "सामान के नाम"),
    "KIRANA_ADD": make_entry("Add to Grocery", "किराने में जोड़ें", "किराना में जोड़ीं"),
    "LEARNERS": make_entry("Learners", "शिक्षार्थी", "सिखावे वाला"),
    "LEARNER_EMPTY_SUB": make_entry("Add learners to track their education.", "शिक्षार्थी जोड़ें।", "सिखावे वाला जोड़ीं।"),
    "LEARNER_NAME": make_entry("Learner Name", "शिक्षार्थी का नाम", "सिखावे वाला के नाम"),
    "LEARNER_NAME_PH": make_entry("e.g. Arjun", "जैसे अर्जुन", "जइसे अर्जुन"),
    "LEARNING_GOALS": make_entry("Learning Goals", "सीखने के लक्ष्य", "सीखे के लक्ष्य"),
    "LEDGER_EMPTY": make_entry("No ledger entries yet.", "अभी कोई खाता नहीं।", "अभी कौनो हिसाब नाही बा।"),
    "LIGHT_MODE": make_entry("Light Mode", "लाइट मोड", "लाइट मोड"),
    "LIGHT_MODE_SHORT": make_entry("Light", "लाइट", "लाइट"),
    "LINKED": make_entry("Linked", "लिंक किया हुआ", "जुड़ल बा"),
    "LINK_DEVICE": make_entry("Link Device", "डिवाइस लिंक करें", "डिवाइस जोड़ीं"),
    "LOADING": make_entry("Loading...", "लोड हो रहा है...", "लोड होत बा..."),
    "LOCATION_LABEL": make_entry("Location", "स्थान", "जगह"),
    "LOGOUT_CLOUD": make_entry("Logout Cloud", "क्लाउड लॉगआउट", "क्लाउड से निकलीं"),
    "LOG_SESSION": make_entry("Log Session", "सत्र लॉग करें", "बइठकी लिखीं"),
    "MARKET_VALUE": make_entry("Market Value", "बाजार मूल्य", "बजार के दाम"),
    "MARK_DONE": make_entry("Mark as Done", "पूर्ण करें", "पूरा कइल"),
    "MARK_PRIVATE": make_entry("Mark Private", "निजी करें", "गुप्त करीं"),
    "MEDICAL_PROFILES": make_entry("Medical Profiles", "चिकित्सा प्रोफाइल", "दवाई के हाल"),
    "MONEY": make_entry("Money", "धन", "रुपिया-पइसा"),
    "MONEY_BALANCE": make_entry("Balance", "शेष राशि", "बचत"),
    "MONEY_EFFICIENCY": make_entry("Efficiency", "दक्षता", "बचत के हाल"),
    "MONEY_EXPENSE": make_entry("Expense", "खर्च", "खर्चा"),
    "MONEY_INCOME": make_entry("Income", "आय", "कमाई"),
    "MONEY_SUBTITLE": make_entry("Family Financial Ledger", "पारिवारिक वित्तीय खाता", "घर के पइसा के हिसाब"),
    "MONTHLY_PAYOUT": make_entry("Monthly Payout", "मासिक भुगतान", "महीना के पैसा"),
    "MONTHLY_SIP": make_entry("Monthly SIP", "मासिक SIP", "महीना के SIP"),
    "MOOD": make_entry("Mood", "मूड", "मिजाज"),
    "MOOD_LABEL": make_entry("How are you feeling?", "आप कैसा महसूस कर रहे हैं?", "रउवा केइसन लागत बा?"),
    "NARRATION_LABEL": make_entry("Narration", "विवरण", "बिबरन"),
    "NETWORK_STATUS": make_entry("Network Status", "नेटवर्क स्थिति", "नेटवर्क के हाल"),
    "NET_PARAM": make_entry("Net", "नेट", "नेट"),
    "NEVATA": make_entry("Nevata", "नेवता", "नेवता"),
    "NEVATA_SUBTITLE": make_entry("Family Occasions & Gifts", "पारिवारिक उत्सव और उपहार", "घर के उत्सव आउर नेग"),
    "NEW_ENTRY": make_entry("New Entry", "नई प्रविष्टि", "नया लिखाई"),
    "NEW_EVENT": make_entry("New Event", "नया आयोजन", "नया उत्सव"),
    "NEW_INVESTMENT": make_entry("New Investment", "नया निवेश", "नया निवेश"),
    "NEW_LEARNER": make_entry("New Learner", "नया शिक्षार्थी", "नया सिखावे वाला"),
    "NEW_TASK": make_entry("New Task", "नया कार्य", "नया काम"),
    "NEXT_STEP_BTN": make_entry("Next", "अगला", "आगे"),
    "NOT_SUPPORTED": make_entry("Not Supported", "समर्थित नहीं", "नाही बा"),
    "NO_DUE_DATE": make_entry("No due date", "कोई नियत तारीख नहीं", "कौनो तारीख नाही"),
    "NO_EVENTS": make_entry("No events yet.", "अभी कोई आयोजन नहीं।", "अभी कौनो उत्सव नाही बा।"),
    "NO_INVESTMENTS": make_entry("No investments yet.", "अभी कोई निवेश नहीं।", "अभी कौनो निवेश नाही बा।"),
    "NO_LEARNERS": make_entry("No learners added yet.", "अभी कोई शिक्षार्थी नहीं।", "अभी कौनो नाही बा।"),
    "NO_RESOURCES": make_entry("No resources added yet.", "अभी कोई संसाधन नहीं।", "अभी कौनो साधन नाही बा।"),
    "NO_RESULTS": make_entry("No results found.", "कोई परिणाम नहीं मिला।", "कौनो परिणाम नाही मिलल।"),
    "NO_SUBJECTS": make_entry("No subjects added yet.", "अभी कोई विषय नहीं।", "अभी कौनो विषय नाही बा।"),
    "OFF_GRID": make_entry("Off-Grid", "ऑफ-ग्रिड", "ऑफ-ग्रिड"),
    "ONBOARD_STAFF": make_entry("Onboard Staff", "स्टाफ जोड़ें", "स्टाफ जोड़ीं"),
    "OPTIONAL": make_entry("Optional", "वैकल्पिक", "जरूरी नाही"),
    "OUR_SHADI": make_entry("Our Wedding", "हमारी शादी", "हमार शादी"),
    "P2P_SYNC": make_entry("P2P Sync", "P2P सिंक", "P2P सिंक"),
    "PANTRY_FULL": make_entry("Pantry Full", "पेंट्री भरी है", "भंडार भरल बा"),
    "PANTRY_STATUS": make_entry("Pantry Status", "पेंट्री स्थिति", "भंडार के हाल"),
    "PAYMENT_HISTORY": make_entry("Payment History", "भुगतान इतिहास", "पैसा देवे के इतिहास"),
    "PEOPLE_COUNT": make_entry("People Count", "लोगों की संख्या", "लोगन के गिनती"),
    "PERMISSION_DENIED_ERROR": make_entry("Permission denied", "अनुमति अस्वीकृत", "अनुमति नाही मिलल"),
    "PNL_PERCENT": make_entry("P&L %", "लाभ हानि %", "फायदा-नुकसान %"),
    "PRESENT": make_entry("Present", "उपस्थित", "हाजिर"),
    "PREV_STEP_BTN": make_entry("Back", "पीछे", "पीछे"),
    "PRIORITY_LABEL": make_entry("Priority", "प्राथमिकता", "जरूरी"),
    "PRIVATE_SUB": make_entry("This entry is private", "यह प्रविष्टि निजी है", "ई लिखाई गुप्त बा"),
    "QTY": make_entry("Qty", "मात्रा", "गिनती"),
    "RECEIVED_TOTAL": make_entry("Received Total", "कुल प्राप्त", "कुल मिलल"),
    "RESOURCES": make_entry("Resources", "संसाधन", "साधन"),
    "RESOURCE_TYPE": make_entry("Resource Type", "संसाधन प्रकार", "साधन के किसिम"),
    "REVIEW_ANALYSIS": make_entry("Review & Analysis", "समीक्षा और विश्लेषण", "समीक्षा"),
    "SAVE_TO_VAULT": make_entry("Save to Vault", "वॉल्ट में सहेजें", "तिजोरी में सेव करीं"),
    "SCANNING": make_entry("Scanning...", "स्कैन हो रहा है...", "स्कैन होत बा..."),
    "SCANNING_SOURCES": make_entry("Scanning sources...", "स्रोत स्कैन हो रहे हैं...", "स्रोत देखत बा..."),
    "SCHOOL_COLL": make_entry("School / College", "स्कूल / कॉलेज", "स्कूल / कॉलेज"),
    "SELECT_MEMBER": make_entry("Select Member", "सदस्य चुनें", "सदस्य चुनीं"),
    "SETUP_MODULES": make_entry("Setup Modules", "मॉड्यूल सेटअप", "मॉड्यूल सेट करीं"),
    "SETUP_PREFERENCES": make_entry("Setup Preferences", "प्राथमिकताएं सेटअप", "पसंद सेट करीं"),
    "SET_PIN_SUB": make_entry("This PIN protects your vault", "यह PIN आपके वॉल्ट को सुरक्षित करता है", "ई PIN रउवा के तिजोरी बचाई"),
    "SET_PIN_TITLE": make_entry("Set Your PIN", "अपना PIN सेट करें", "अपना PIN सेट करीं"),
    "SIP_VOLUME": make_entry("SIP Volume", "SIP मात्रा", "SIP के रकम"),
    "SMART_LEARNING": make_entry("Smart Learning", "स्मार्ट लर्निंग", "होशियार पढ़ाई"),
    "SMART_SHOPPING": make_entry("Smart Shopping", "स्मार्ट शॉपिंग", "होशियार खरीदारी"),
    "STAFF_ROSTER": make_entry("Staff Roster", "स्टाफ रोस्टर", "स्टाफ के लिस्ट"),
    "STEP_INDICATOR": make_entry("Step {current} of {total}", "चरण {current} / {total}", "चरण {current} / {total}"),
    "STORE_CATEGORIES": make_entry("Store Categories", "स्टोर श्रेणियाँ", "दुकान के किसिम"),
    "STUDY_BUDDY": make_entry("Study Buddy", "स्टडी बडी", "पढ़ाई के साथी"),
    "SUBJECTS": make_entry("Subjects", "विषय", "विषय"),
    "SUBJECT_CAT_PH": make_entry("e.g. Science", "जैसे विज्ञान", "जइसे विज्ञान"),
    "SUBJECT_NAME_PH": make_entry("e.g. Mathematics", "जैसे गणित", "जइसे गणित"),
    "SUGGESTED": make_entry("Suggested", "सुझाए गए", "सुझाव"),
    "SUPPORT_STAFF": make_entry("Support Staff", "सहायक कर्मचारी", "सहायक स्टाफ"),
    "SYSTEM_LANG": make_entry("System Language", "सिस्टम भाषा", "सिस्टम के भाषा"),
    "SYSTOLIC": make_entry("Systolic", "सिस्टोलिक", "सिस्टोलिक"),
    "TAGS_LABEL": make_entry("Tags", "टैग", "टैग"),
    "TASKS": make_entry("Tasks", "कार्य", "काज-काम"),
    "TASKS_ADD": make_entry("Add Task", "कार्य जोड़ें", "काम जोड़ीं"),
    "TASKS_CATEGORY": make_entry("Category", "श्रेणी", "किसिम"),
    "TASKS_DONE": make_entry("Done", "पूर्ण", "पूरा"),
    "TASKS_DUE_DATE": make_entry("Due Date", "नियत तिथि", "तारीख"),
    "TASKS_EMPTY": make_entry("No tasks yet.", "अभी कोई कार्य नहीं।", "अभी कौनो काम नाही बा।"),
    "TASKS_PENDING": make_entry("Pending", "लंबित", "बाकी"),
    "TASKS_PLANNED": make_entry("Planned", "नियोजित", "तय"),
    "TASKS_ROUTINE": make_entry("Routine", "नियमित", "रोजाना"),
    "TASKS_SUBTITLE": make_entry("Family Task Manager", "पारिवारिक कार्य प्रबंधक", "घर के काम के लिस्ट"),
    "TASKS_URGENT": make_entry("Urgent", "अत्यावश्यक", "जरूरी"),
    "TASK_DESC_LABEL": make_entry("Description", "विवरण", "बिबरन"),
    "TASK_TITLE_LABEL": make_entry("Task Title", "कार्य शीर्षक", "काम के नाम"),
    "THEIR_SHADI": make_entry("Their Wedding", "उनकी शादी", "उनकर शादी"),
    "TODAY": make_entry("Today", "आज", "आज"),
    "TOO_MANY_ATTEMPTS": make_entry("Too many attempts. Try later.", "बहुत अधिक प्रयास। बाद में प्रयास करें।", "बहुत कोशिश भइल। बाद में आईं।"),
    "TOTAL_PROFIT": make_entry("Total Profit", "कुल लाभ", "कुल फायदा"),
    "TOTAL_VALUE": make_entry("Total Value", "कुल मूल्य", "कुल दाम"),
    "TRACKING_ASSETS": make_entry("Tracking Assets", "संपत्ति ट्रैकिंग", "संपत्ति देखत बा"),
    "UNIT": make_entry("Unit", "इकाई", "यूनिट"),
    "UPCOMING": make_entry("Upcoming", "आगामी", "आगे"),
    "VAULT_NAME_LABEL": make_entry("Vault Name", "वॉल्ट का नाम", "तिजोरी के नाम"),
    "VAULT_NAME_PH": make_entry("e.g. Mallah Parivar", "जैसे मल्लाह परिवार", "जइसे मल्लाह परिवार"),
    "VERIFIED": make_entry("Verified", "सत्यापित", "जाँचल गइल"),
    "VYAVASTHA": make_entry("Vyavastha", "व्यवस्था", "व्यवस्था"),
    "WEALTH_PORTFOLIO": make_entry("Wealth Portfolio", "धन पोर्टफोलियो", "धन के पोर्टफोलियो"),
    "WEATHER_LABEL": make_entry("Weather", "मौसम", "मौसम"),
    "WEATHER_NONE": make_entry("No weather data", "मौसम डेटा नहीं", "मौसम के जानकारी नाही"),
    "WEIGHT": make_entry("Weight", "वजन", "वजन"),
    "WE_ARE_AHEAD": make_entry("We are ahead!", "हम आगे हैं!", "हम आगे बानी!"),
    "WRONG_PIN_ERROR": make_entry("Incorrect PIN", "गलत PIN", "गलत PIN"),
    "legal.terms.title": make_entry("Terms of Sovereignty", "संप्रभुता की शर्तें", "संप्रभुता के शर्त"),
    "legal.terms.desc.title": make_entry("Description", "विवरण", "बिबरन"),
    "legal.terms.desc.content": make_entry("Kutumbly is a local-first, sovereign family operating system.", "कुटुंबली एक स्थानीय-प्रथम, संप्रभु पारिवारिक ऑपरेटिंग सिस्टम है।", "कुटुंबली एगो लोकल-फर्स्ट, संप्रभु परिवार के OS बा।"),
    "legal.terms.sovereignty.title": make_entry("Sovereignty", "संप्रभुता", "संप्रभुता"),
    "legal.terms.sovereignty.content": make_entry("You own your data. No cloud, no server, no compromise.", "आपका डेटा आपका है। कोई क्लाउड नहीं।", "रउवा के डेटा रउवा के हवे। कौनो क्लाउड नाही।"),
    "legal.terms.responsibility.title": make_entry("Your Responsibility", "आपकी जिम्मेदारी", "रउवा के जिम्मेदारी"),
    "legal.terms.responsibility.content": make_entry("You are responsible for your own vault and data.", "आप अपने डेटा के लिए जिम्मेदार हैं।", "रउवा अपना डेटा के जिम्मेदार हईं।"),
    "legal.terms.ip.title": make_entry("Intellectual Property", "बौद्धिक संपदा", "बौद्धिक संपदा"),
    "legal.terms.ip.content": make_entry("Kutumbly and its design are © 2026 AITDL Network.", "कुटुंबली और इसका डिज़ाइन © 2026 AITDL Network।", "कुटुंबली © 2026 AITDL Network के बा।"),
    "legal.terms.liability.title": make_entry("Liability", "दायित्व", "जिम्मेदारी"),
    "legal.terms.liability.content": make_entry("We are not liable for any data loss from device failure.", "डिवाइस विफलता से डेटा हानि के लिए हम उत्तरदायी नहीं हैं।", "डिवाइस खराब होने से डेटा के नुकसान खातिर हम जिम्मेदार नाही।"),
    "legal.terms.acceptance.title": make_entry("Acceptance", "स्वीकृति", "स्वीकृति"),
    "legal.terms.acceptance.content": make_entry("By using Kutumbly, you accept these terms.", "कुटुंबली का उपयोग करके, आप इन शर्तों को स्वीकार करते हैं।", "कुटुंबली इस्तेमाल क के रउवा इन शर्तन से राजी बानी।"),
}

import json, re

i18n_file = r'd:\IMP\GitHub\kutumbly\lib\i18n.ts'

with open(i18n_file, 'r', encoding='utf-8') as f:
    content = f.read()

# Build new entries block
new_block = "\n  // Auto-generated missing keys\n"
for key, vals in MISSING.items():
    parts = ", ".join(f'{lang}: "{v.replace(chr(34), chr(39))}"' for lang, v in vals.items())
    new_block += f'  "{key}": {{ {parts} }},\n'

# Insert before the closing }; of DICTIONARY
# Find the last }; that closes DICTIONARY
insert_idx = content.rfind("\n};")
if insert_idx == -1:
    print("ERROR: Could not find closing }; for DICTIONARY!")
else:
    content = content[:insert_idx] + new_block + content[insert_idx:]
    with open(i18n_file, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"SUCCESS: Inserted {len(MISSING)} missing keys.")
